name: bookly_app
description: Bookly app with MVVM and Bloc for exploring books.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  cached_network_image: ^3.2.3
  connectivity_plus: ^3.0.3
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  dio: ^5.0.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  fluttertoast: ^8.2.1
  font_awesome_flutter: ^10.4.0
  get_it: ^7.2.0
  go_router: ^6.0.9
  google_fonts: ^4.0.3
  hive_flutter: ^1.1.0
  shimmer: ^2.0.0
  url_launcher: ^6.1.9

dev_dependencies:
  build_runner: null
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  hive_generator: null

flutter:

  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
  #   - images/a_dot_ham.jpeg
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: GT Sectra
      fonts:
        - asset: assets/fonts/GT_Sectra_Fine_Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
